### PR TITLE
Fixes #22 : [Fix] Dates : fix the date timezone

### LINKED ISSUE #22: [Fix] Dates : timezone not working
It seems that the date parser works but doesn't take in account the timezone

### PR DESCRIPTION
**Pull request by jcholin**
The time zone is taken in account now

### CODE REVIEW

File: sdk-api/src/main/java/com/xee/api/Xee.java [hunk 1]
```diff
@@ -93,6 +102,27 @@
     private CarsService carsService;
     private TripsService tripsService;
 
+    private static class DateDeserializer implements JsonSerializer<Date>, JsonDeserializer<Date> {
```
Comment (qk7b) [inline sdk-api/src/main/java/com/xee/api/Xee.java:108]: A java comment on what it does would be great

File: sdk-api/src/main/java/com/xee/api/Xee.java [hunk 2]
```diff
@@ -93,6 +102,27 @@
...
+        @Override
+        public synchronized Date deserialize(JsonElement element, Type arg1, JsonDeserializationContext arg2) throws JsonParseException {
+            final String date = element.getAsString();
+            SimpleDateFormat formatter = new SimpleDateFormat(DATE_FORMAT, Locale.US);
+            formatter.setTimeZone(TimeZone.getTimeZone("UTC"));
+
+            try {
+                return formatter.parse(date);
+            } catch (ParseException e) {
+                return null;
```
Comment (qk7b) [inline sdk-api/src/main/java/com/xee/api/Xee.java:127]: Maybe you can add a Log or something

**Review by qk7b — CHANGES_REQUESTED** [review]

**Review by qk7b — APPROVED** [review]

**Comment by jcholin** [comment]
It closes #22
